### ISSUE TITLE
Front-end app web para emitir la constancia PDF

### ISSUE THREAD

**Issue by ldrojas** [edenia/constancias-municipales#4]
- [x] Contenido #13 
- [x] Diseño #14 
- [x] Conexión formulario con backend #15
- [x] Captcha #16 
- [x] Snackbar ingreso de datos #19 
- [x] Pantalla agradecimiento #20
- [x] Email #21
- [x] Aplicar diseño y contenido #24
